import Head from 'next/head'
import {Header} from '../components/Header'
import {Post} from "../components/Post";


export default function Home() {
    return (
        <div>
            <Head>
                <title>RJournal</title>
                <meta name="description"
                      content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <Header/>
            <div className={'content'}>
                <Post/>
                <Post/>
                <Post/>
            </div>
        </div>

    )
}